
version: '3'
services:
  traefik:
      image: traefik
      command: -c /dev/null --web --docker
      labels:
        - "traefik.enable=false"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  eureka:
    image: soa/eureka-server
    labels:
      - "traefik.port=8761"
      - "traefik.backend=eureka"
      - "traefik.frontend.rule=PathPrefixStrip:/eureka"
    depends_on:
      - traefik

  zuul:
    image: soa/zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/zuul"
    depends_on:
      - traefik
      - eureka

  recruitment:
    image: soa/recruitment
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - eureka
      - postgres
      - zuul
    links:
      - postgres
      - eureka

  demoapp:
    image: soa/demo-app
    labels:
      - "traefik.enable=false"
    depends_on:
      - traefik
      - eureka
      - zuul
    links:
      - eureka

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soa-recruitment-db
