eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: false
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

zuul:
  ignoredServices: '*'
  routes:
    gateway: 
      path: /gateway/**
      sensitive-headers:
    eureka: /eureka/**
    login:
      path: /login/**
      sensitive-headers:


management:
  security:
    enabled: false
